config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "splashes/index"

  resources :groups
  resources :entities

  unauthenticated do
    root "splashes#index"
  end

  authenticated do
    root "groups#index", as: :authenticated_root
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_up_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @entity = Entity.new
    @groups = Group.all.where(user_id: current_user.id)
  end

  def create
    @entity = Entity.create(entity_params)
    @entity.user_id = current_user.id
    respond_to do |format|
      if @entity.save
        format.html do
          redirect_to group_url(Group.find(@entity.group_id)), notice: 'Entity was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:public]

  def index
    @groups = Group.where(user_id: current_user.id).order('id DESC')
  end

  def show
    @entities = Entity.all.where(group_id: @group.id).order('id DESC')
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_amount_helper(entities)
    entities.reduce(0) { |sum, entity| sum + entity.amount }
  end
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/entities/new.html.erb
<section class="text-center vh-100">
    <%= render "shared/header2", page_title: "New Expense" %>

    <div class="mx-2">
        <%= form_with model: @entity do |f| %>
            <div class="my-3 px-3">
                <%= f.text_field :name, placeholder: "Expense Name", require: true, class: 'w-100 bg-gray-100 p-2' %>
            </div>
            <div class="my-3 px-3">
                <%= f.number_field :amount, in: 1.0..1000.0, step: 0.5, placeholder: "Amount", require: true, class: 'w-100 bg-gray-100 p-2' %>
            </div>
            <div class="my-3 px-3">
                <%= f.collection_select :group_id, @groups, :id, :name,:prompt => true, require: true, class: 'w-100 bg-gray-100 p-2' %>
            </div>
            <div class="form-group">
                <%= f.submit "Submit", class: "btn btn-primary px-4"%>
            </div>
        <% end %>
    </div>

</section>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |f| %>
    <div class="my-3 px-3">
        <%= f.text_field :name, class: 'form-control', placeholder: "Category Name", require: true, class: 'w-100 bg-gray-100 p-2' %>
    </div>
    <div class="my-3 px-3">
        <%= f.select :icon, {"🛒" => "https://cdn-icons-png.flaticon.com/512/891/891462.png", "🎮" =>"https://cdn-icons-png.flaticon.com/512/808/808439.png", "🚌" => "https://cdn-icons-png.flaticon.com/512/1034/1034795.png","💄"=>"https://img.icons8.com/external-wanicon-flat-wanicon/344/external-make-up-beauty-cosmetics-wanicon-flat-wanicon.png"}, {}, class: 'form-control w-100 bg-gray-100 p-2' %>
    </div>
    <div class="form-group">  
        <%= f.submit "Save Category", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/groups/_group.html.erb
<div class="row card m-3 ps-1 pe-3 rounded">
  <div class="col-sm-4 m-0 p-0 d-flex align-items-center justify-content-center w-100">
    <p class=""> <%= image_tag group.icon, class:"group___icons"%></p>
  </div>
  <div class="col-sm-8 d-flex justify-content-between w-100 m-0 p-0">      
    <ul class="d-flex flex-column align-items-start justify-content-start">
      <li> <h4 class="py-2"><%= link_to group.name, group_path(group), class: "def__txtColor text-uppercase" %></h4></li>
      <li> <p> <%= group.created_at.strftime("%d-%b-%Y")%></p></li>
    </ul>
    <ul class="d-flex flex-column justify-content-start m-0 p-0">
      <li><p class="py-2 text-center fw-bold text-uppercase">Total : $<%= total_amount_helper(Entity.all.where(group_id:group.id)) %></p></li>      
    </ul>
  </div>
</div>

 
  

app/views/groups/index.html.erb
<section class="text-center vh-100">
    <%= render "shared/header", page_title: "Transactions" %>   

    <% if flash.notice %>
        <p class="notice"><%= notice %></p>
    <% end %>

    <div class="">
        <% if @groups.any?%>
            <% @groups.each do |group| %>
                <%= render group %>
            <% end %>
        <% else %>
            <p class="p-2 m-2 h3">There is no category added!!!</p>
        <% end %>            
    </div>

    <%= render "shared/footer", link_text: "Add a new category", link_url: new_group_path %>
</section>

app/views/groups/new.html.erb
<section class="text-center vh-100">
    <%= render "shared/header2", page_title: "New Category" %>
    <br/><br/>
    <%= render "form", group: @group %>
</section>

app/views/groups/show.html.erb
<section class="text-center vh-100">
    <%= render "shared/header2", page_title: "Details" %>

    <% if flash[:notice] %>
        <p class="notice" role="alert"><%= notice %></p>
    <% end %>
    <%= render @group %>
    <div class="card m-3 rounded pe-4">
    <% if @entities.any?%>
    <% @entities.each do |entity| %>
            <div class="container-fluid mx-2 px-2 bg-white border-bottom">
                <p class="px-3 pt-2 d-flex justify-content-left fw-bold"><%= entity.name.capitalize %></p>
                <p class="px-3 pb-1 mb-0 d-flex justify-content-left">Transactionº<%= entity.created_at.to_time.to_i %></p>
                <p class="px-3 pb-1 mb-0 d-flex justify-content-left"><span class="fa fa-calendar"></span> <span class="mx-1"><%= entity.created_at %></span></p>
            </div>
            <div class="container-fluid mx-2 px-2 bg-white border-bottom">
                <p class="px-4 py-2 m-0 d-flex justify-content-between">
                    <strong>Amount:</strong>
                    $<%= entity.amount %>
                </p>
            </div>        
    <% end %>
    <% else %>
            <p class="p-2 m-2 h3">No Records Found!</p>
    <% end %> 
    </div>

    <%= render "shared/footer", link_text: "Add new transaction", link_url: new_entity_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/46794738cc.js" crossorigin="anonymous"></script>
    <title>Startup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg__sec p-3 w-100 fixed-bottom">
    <%= link_to link_text, link_url, class: 'btn btn-outline fw-bold col-12 text-uppercase text-white border-white' %>
</footer>

app/views/shared/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark m-0 p-0">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
        </button> 
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#" >Home</a></li>
                <li class="nav-item">
                    <% if user_signed_in? %> 
                        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
                    <% end %>
                </li>
            </ul>        
        </div>
    </nav>
    <p class="text-uppercase justify-content-center"><%=page_title%></p>
    <div class="justify-content-end pe-3"><i class="fa fa-search"></i></div>
</header>

app/views/shared/_header2.html.erb
<header class="header--sec">
    <%= link_to "javascript:history.back()" do %>
        <i class="fa fa-arrow-left text-white"></i>
    <%end%>
    <p class="text-uppercase justify-content-center"><%=page_title%></p>
    <div class="justify-content-end pe-3">
    <%= link_to groups_path do %>
        <i class="fa fa-home text-white"></i>
    <%end%>
    </div>
</header>

app/views/splashes/index.html.erb
<section class="container splash">
  <div class="mb-5 rounded-0">
    <h1 class="display-1 title fw-bold fst-italic text-center mb-5">
    Budget-App
    </h1>
  </div>
  <div class="mt-5">
    <%= link_to 'LOG IN', user_session_path, class: 'btn btn-primary w-100 my-3 p-3' %><br>
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-primary w-100 mb-4 p-3' %>
  </div>
</section>